config/routes.rb
Rails.application.routes.draw do
  resources :entries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
= form_with(model: entry, local: true) do |form|
  - if entry.errors.any?
    #error_explanation
      %h2
        = pluralize(entry.errors.count, "error")
        prohibited this entry from being saved:
      %ul
        - entry.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :title
    = form.text_field :title

  .field
    = form.label :body
    = form.text_area :body

  .actions
    = form.submit

app/views/entries/edit.html.haml
%h1 Editing Entry

= render 'form', entry: @entry

= link_to 'Show', @entry
|
= link_to 'Back', entries_path

app/views/entries/index.html.haml
%p#notice= notice

%h1 Entries

%table
  %thead
    %tr
      %th Title
      %th Body
      %th{colspan: "3"}
  %tbody
    - @entries.each do |entry|
      %tr

        %td= entry.title
        %td= entry.body
        %td= link_to 'Show', entry
        %td= link_to 'Edit', edit_entry_path(entry)
        %td= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Entry', new_entry_path

app/views/entries/new.html.haml
%h1 New Entry

= render 'form', entry: @entry

= link_to 'Back', entries_path

app/views/entries/show.html.haml
%p#notice= notice

%p
  %strong
    Title:
    = @entry.title

%p
  %strong
    Body:
    = @entry.body

= link_to 'Edit', edit_entry_path(@entry)
|
= link_to 'Back', entries_path

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %title RailsAssignmentCrud2
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield